### ISSUE TITLE
video loop option

### ISSUE THREAD

**Issue by darkyndy** [darkyndy/YoutubeVideoPreview#4]
It will be nice i you are watching video to have option to loop it.

Loop video should have option to:
- enable/disable loop inside page;
- set start time;
- set end time;

Loop option should have option to activate/deactivate functionality throw options page.

**Comment by iiiGerardoiii** [comment]
The latest HTML5 player comes with an option to loop the video, by right clicking on it:
![captura de pantalla 2016-08-03 02 54 17](https://cloud.githubusercontent.com/assets/6264194/17358225/6fce305c-5926-11e6-9060-3e83f32be228.png)

**Comment by darkyndy** [comment]
Yep, closing this, no longer needed.
