### ISSUE TITLE
Adding up/down vote counts would increase usability.

### ISSUE THREAD

**Issue by mzso** [darkyndy/YoutubeVideoPreview#7]
Hello!
It would help determine the importance of the ratings bar. One down or up vote is not much relevant, but seeing only a full green/red bar doesn't show that. 

![youtube votes](https://f.cloud.github.com/assets/4479090/1089494/f4b1f5ec-1644-11e3-9aa0-3010d87b49d3.png)

**Comment by darkyndy** [comment]
With latest YouTube design changes, this request is hard to implement as it may produce more bugs than improve extension usability.

At this moment if you mouse hover rating bar added by extension you will see something like: "173 likes from 175 rating (98.86%)"
