### ISSUE TITLE
ff preview thumbnail is smaller than window

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [darkyndy/YoutubeVideoPreview#9]
See screenshot

![schermata-3](https://cloud.githubusercontent.com/assets/10689739/6432606/651b8c18-c057-11e4-826a-f6919118b597.png)

**Comment by darkyndy** [comment]
nice one :) I will look into it.

**Comment by darkyndy** [comment]
Fixed, will be available with version 2.2.4
